# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 377)
        MainWindow.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-1, 0, 651, 331))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 0, 631, 71))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.Vid_URL = QtWidgets.QLineEdit(self.frame_2)
        self.Vid_URL.setGeometry(QtCore.QRect(50, 150, 451, 31))
        self.Vid_URL.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.Vid_URL.setObjectName("Vid_URL")
        self.d_v = QtWidgets.QPushButton(self.frame_2)
        self.d_v.setGeometry(QtCore.QRect(510, 150, 121, 31))
        self.d_v.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.d_v.setObjectName("d_v")
        self.PL_URL = QtWidgets.QLineEdit(self.frame_2)
        self.PL_URL.setGeometry(QtCore.QRect(50, 260, 451, 31))
        self.PL_URL.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.PL_URL.setObjectName("PL_URL")
        self.d_pl = QtWidgets.QPushButton(self.frame_2)
        self.d_pl.setGeometry(QtCore.QRect(510, 260, 121, 31))
        self.d_pl.setStyleSheet("border-radius: 10px;\n"
"background-color:rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255)")
        self.d_pl.setObjectName("d_pl")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(50, 220, 171, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 171, 31))
        self.label_3.setObjectName("label_3")
        self.v_stat = QtWidgets.QLabel(self.frame_2)
        self.v_stat.setGeometry(QtCore.QRect(420, 190, 81, 21))
        self.v_stat.setStyleSheet("color: rgb(255, 255, 255)")
        self.v_stat.setObjectName("v_stat")
        self.pl_stat = QtWidgets.QLabel(self.frame_2)
        self.pl_stat.setGeometry(QtCore.QRect(420, 300, 81, 21))
        self.pl_stat.setStyleSheet("color: rgb(255, 255, 255)")
        self.pl_stat.setObjectName("pl_stat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 645, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Youtube Video/Playlist Downloader", "Youtube Video/Playlist Downloader"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Youtube Video / Playlist Downloader</span></p></body></html>"))
        self.d_v.setText(_translate("MainWindow", "Download"))
        self.d_pl.setText(_translate("MainWindow", "Download"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Download PLaylist</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Download Video</span></p></body></html>"))
        self.v_stat.setText(_translate("MainWindow", "Status"))
        self.pl_stat.setText(_translate("MainWindow", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
